# Generated by Django 5.1.4 on 2025-03-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellen',
            name='done',
            field=models.CharField(choices=[('doing', 'DOING'), ('done', 'DONE')], max_length=5),
        ),
    ]
